---
author: "Антон Ангельгардт"
---

# Числа {#ch-apx-numbers}

{{< include ../../../../shared/includes/math-symbols.qmd >}}

```{r opts, echo=FALSE, eval=TRUE, message=FALSE, warning=FALSE}
knitr::opts_chunk$set(echo = FALSE, eval = TRUE, message = FALSE, warning = FALSE, error = TRUE, cache = TRUE)
```

:::{.intro}
Казалось бы, зачем говорить о числах? Все мы каждый день сталкиваемся с невероятным их количеством, при этом как-то более-менее успешно управляясь с ними. Стоит ли тратить время --- притом немалое, судя по скролл-бару --- на обсуждение столь хорошо знакомой нам вещи?

С одной стороны, числа --- безусловно, нечто интуитивно нам понятное. Более того, мы со школы усвоили определенные принципы и правила работы с ними. С другой стороны, числа являют собой нечто в определенной мере загадочное и непонятное --- даже те, относительно которых вроде бы всё более чем ясно.

В этом приложении мы познакомимся с числами. Может быть, вновь, а возможно и впервые. Мы посмотрим и на практическую, и на историческую, и на психологическую сторону чисел, при этом, разумеется, не оставив в стороне и строгую математическую сторону. Полагаю, что даже имея хороший математический бэкграунд, вы сможете найти здесь интересные детали.
:::


## Что есть число? {#sec-numbers-what-number-is}



## Натуральные числа {#sec-numbers-setN}


:::{.callout-note title="Ноль как натуральное число"}
Полагаю, включение нуля во множество натуральных чисел требует некоторых пояснений, ведь со школы нас выучили, что «ноль не является натуральным числом!!!».

Действительно, если мы определяем натуральные числа как использующиеся при счёте предметов, довольно трудно посчитать какие-либо предметы, когда их *ноль* --- то есть вовсе нет. Скажем, как нам пересчитать студентов на паре, если никто не пришёл? «Пересчитать» в этом контексте значит «перенумеровать», иначе говоря, обозначить, кто есть *первый*, кто *второй*, кто *третий* и т. д. Так, мы вполне способы пересчитать банки энергетика, выпитые в ночь перед экзаменом (*первый* энергетик, *второй* энергетик, …, *двадцать шестой* энергетик, ...). При этом если мы попробуем выпить *нулевой* энергетик… то он моментально станет *первым*. Таким образом, в данном подходе ноль **не является** натуральным (естественным) числом.

Однако мы можем поставить несколько иную задачу: не пытаться перенумеровать --- то есть сказать, **каким** является объект по счёту --- а посмотреть на ситуацию в общем, чтобы узнать **сколько** банок энергетика было выпито (*один* энергетик, *два* энергетика, …, *двадцать шесть* энергетиков, …). В этом случае вполне естественной является ситуация, когда не было выпито ни одного стимулирующего напитка. Такую ситуацию как раз и будет описывать *ноль* --- «выпито *ноль* энергетиков». Да, конечно, с позиции литературного языка конструкция странновата, но ситуацию отражает вполне точно. Получается, в данном подходе ноль **является** натуральным (естественным) числом.

Помимо интуиции, рассмотренной в примерах выше, в разных разделах математики натуральные числа могут содержать или не содержать ноль в зависимости от того, насколько это удобно и не приводит ли это к каким-либо противоречиям. Так, в теории множеств обычно рассматривают натуральные числа, включая ноль --- это сохраняет соответствие между мощностью множеств и натуральными числами, в частности, между мощностью пустого множества и нулём. В то же время в матане при индексации рядов (нумерации слагаемых) удобнее начинать с единицы. Впрочем, если присмотреться, видно соответствие с интуитивными примерами: мощность множества как «количество элементов» --- ноль естественен, нумерация слагаемых как «порядок элементов» --- ноль не очень естественен.
:::


В силу такого положения дел и во избежании неоднозначности в математике введено два обозначения [@iso-math, 4]:

- $\setN = \{0, 1, 2, 3, \ldots \}$
- $\setN^\star = \{ 1, 2, 3, \ldots\}$

В книге принято несколько иное разделение (см. @nte-setN):

{{< include ../_partials/nte-setN.qmd >}}

:::{.callout-note .history .column-margin title="История нуля"}
Ноль сам по себе довольно интересный феномен[^zero-history].


[^zero-history]: Об истории нуля есть [хорошее видео](https://youtu.be/ZH5d_g_Xa_s?si=DFsUFaNyYq-YrriG) на канале [Vital Math](http://www.youtube.com/@vKoren6174).
:::

### Аксиомы Пеано {#setN-peano}

ПЕРЕДЕЛАТЬ на Z+, отдельно рассмотреть задание натуральных чисел через множества, показать, что в двух подходах нет противоречий

Сам Дж. Пеано сформулировал аксиомы для $\setNstar$ [@peano-arithm], однако мы рассмотрим их в современном изложении для $\setN$ [@tao-analysisI].


:::{#prp-axiom-peano}
**(Аксиомы Пеано)**

1. $0$ является натуральным числом.

$$
0 \in \setN
$${#eq-peano1}

2. За каждым натуральным числом следует натуральное число.

$$
n \in \setN \Rightarrow S(n) \in \setN
$${#eq-peano2}

3. $0$ не следует ни за каким натуральным числом.

$$
\nexists \, n \in \setN : S(n) = 0
$${#eq-peano3}

4. Если натуральное число $a$ непосредственно следует как за числом $b$, так и за числом $c$, то $b$ и $c$ являются одним и тем же числом.

$$
\big( S(b) = a \wedge S(c) = a \big) \Rightarrow b = c
$${#eq-peano4}

5. [*Аксиома индукции*] Если какое-либо предположение доказано для $0$ (*база индукции*) и если из допущения, что оно верно для натурального числа $n$, следует, что оно верно для следующего за $n$ натурального числа (*шаг индукции, индукционный переход*), то это предположение верно для всех натуральных чисел.

$$
P(0) \wedge \forall n \Big( P(n) \Rightarrow P\big( S(n) \big) \Big) \Rightarrow \forall n \in \setN \; P(n)
$${#eq-peano5}

:::

### Отношения в натуральных числах {#setN-rel}

### Операции в натуральных числах {#setN-ops}

#### Сложение {#setN-ops-sum}

$$
a + b = 
a + \underbrace{1 + 1 + \ldots + 1}_b = 
\underbrace{1 + 1 + \ldots + 1}_a + b = 
\underbrace{1 + 1 + \ldots + 1}_a + \underbrace{1 + 1 + \ldots + 1}_b
$$


:::{#prp-num-N-sum-commut}
$$
a + b = b + a
$$
:::

:::{#prp-num-N-sum-assoc}
$$
(a + b) + c = a + (b + c)
$$
:::


#### Умножение {#setN-ops-prod}

$$
a \cdot b = \underbrace{a + a + \ldots + a}_b
$$

#### Возведение в степень {#setN-ops-pow}

$$
a^b = \underbrace{a \cdot a \cdot \ldots \cdot a}_b
$$

<!-- move to .column-margin when done -->
::::{.column-body}
:::{.callout-note collapse=true title="Гипероператор"}
Текст о понятии гипероператора.
:::
::::

#### Вычитание {#setN-ops-sub}

$$
a - b \defin{=} c \equi c + b = a
$$

#### Деление {#setN-ops-div}

$$
a \div b \defin{=} c \equi c \cdot b = a
$$

#### Извлечение корня {#setN-ops-sqr}

$$
\sqrt[n]{a} \defin{=} b \equi b^n = a
$$

Как вторую обратную операцию к возведению в степень уместно было бы обсудить логарифм, но по ряду причин мы этого делать здесь не будем.

:::{.callout-note appearance="minimal" collapse=true title="Ряд причин, по которым мы не будем обсуждать логарифм здесь"}

1. **Практическая причина**

2. **Историческая причина**
:::










## Целые числа {#sec-numbers-setZ}

$$
\setZ
$$


## Рациональные числа {#sec-numbers-setQ}

$$
\setQ
$$


## Вещественные числа {#sec-numbers-setR}

$$
\setR
$$


## Комплексные числа {#sec-numbers-setС}

$$
\setC
$$
