---
author: "Антон Ангельгардт"
---

# Обозначения {#ch-notation .unnumbered}

{{< include ../../../../shared/includes/math-symbols.qmd >}}

```{r opts, echo=FALSE, eval=TRUE, message=FALSE, warning=FALSE}
knitr::opts_chunk$set(echo = FALSE, eval = TRUE, message = FALSE, warning = FALSE, error = TRUE, cache = TRUE)
```

:::{.intro}
Здесь представлены обозначения, используемые в этой книге. Уделите пару минут, чтобы вы могли быстрее ориентироваться в обилии материала.
:::

<!---
## Некий персонаж {#sec-notation-person}
--->

## Лейблы {#seq-notation-labs}

### Раздел для начинающих {#seq-notation-labs-novice .lab-novice}

### Раздел для что-то слышавших {#seq-notation-labs-junior .lab-junior}

### Раздел для что-то знаюших {#seq-notation-labs-middle .lab-middle}

### Раздел для шарящих {#seq-notation-labs-senior .lab-senior}

### Раздел для преисполнившихся {#seq-notation-labs-expert .lab-expert}


## Блоки {#sec-notation-callouts}

### Восклицающие блоки {#sec-notation-callouts-excl}

::::{layout-ncol=2}

:::{.callout-note .myth title="Миф"}
Это миф.
:::

:::{.callout-warning}
Это предупреждение.
:::

:::{.callout-caution}
Это осторожность.
:::

:::{.callout-important}
Это важность.
:::

::::


### Информационные блоки {#sec-notation-callouts-info}

::::{layout-ncol=2}

:::{.callout-note}
Это заметка.
:::

:::{.callout-tip}
Это совет.
:::

:::{.callout-note .dataset title="Датасет"}
Это датасет.
:::

:::{.callout-note .case title="Кейс"}
Это кейс.
:::

:::{.callout-note .history title="История"}
Это история.
:::

:::{.callout-note .person title="Персона"}
Это персона.
:::

::::





## Математика {#sec-notation-math}

### Математические блоки {#sec-notation-math-blocks}

:::{#def-notation}
Любое **понятие** необходимо определить, чтобы ясно обозначить, что оно собой представляет. Так оформляется строгое определение. В тексте можно встретить и другие определения, не оформленные в таком формате, когда нет задачи определить что-либо строго.
:::

:::{#thm-debug}
**(с названием, если оно имеется)**

Это теорема.
:::

:::{#lem-notation}
**(возможно, тоже с названием)**

Это лемма. Вспомогательное утверждение, использующееся для доказательства больших теорем.
:::

:::{#prp-notation}
Это утверждение.
:::

:::{#cor-notation}
Это следствие, которое получается из теоремы, леммы или утверждения. Требует доказательства.
:::

:::{.proof}
Это доказательство теоремы, леммы, утверждения или следствия.
:::

<!---
:::{#cnj-notation}
Это гипотеза (предположение).
:::
--->

:::{#exm-notation}
Это пример.
:::

:::{#exr-notation}
Это упражнение (задание).
:::

:::{.solution}
Это решение.
:::

:::{#sol-notation}
Это нумерованное решение.
:::

:::{.remark}
Это замечание.
:::

:::{#rem-notation}
Это нумерованное замечание.
:::

:::{#alg-notation}
Это алгоритм.
:::



### Математические руны {#sec-notation-math-symbols}

:::{.callout-tip}
Этот раздел можно пропустить. Математические обозначения вводятся постепенно по ходу книги, сопровождаясь необходимыми пояснениями. К данному разделу можно будет обратиться, если вы забудете, что именно обозначает тот или иной символ.
:::

:::{.callout-note appearance="simple"}
Используемые обозначения преимущественно поддерживаются стандартом ISO 80000-2:2019 [@iso-math]. Незначительные отклонения от стандарта обусловлены стремлением избежать потенциальных неоднозначностей. Для случаев, отклоняющихся от стандарта, приведены пояснения и обоснования.
:::


### Общие символы {#sec-notation-math-symbols-misc}


#### Отношения

| Знак, символ, запись | Значение, словесный эквивалент | Комментарии |
|:-----:|:-----|:-----|
| $a = b$ | $a$ равно $b$ |(см. @nte-eqdef)|
| $a \equiv b$ | $a$ тождественно равно $b$ ||
| $a \neq b$ | $a$ не равно $b$ ||
| $a := b$ | обозначим $b$ как $a$ |(см. @nte-eqdef)|
| $a \defin= b$ | $a$ равно $b$ по определению |(см. @nte-eqdef)|
| $a \approx b$ | $a$ приблизительно равно $b$ ||
| $a \simeq b$ | $a$ асимптотически равно $b$ ||
| $a \sim b$ | $a$ эквивалентно $b$ ||
| $a \propto b$ | $a$ пропорционально $b$ ||
| $a < b$ | $a$ (строго) меньше $b$ ||
| $a > b$ | $a$ (строго) больше $b$ ||
| $a \leq b$ | $a$ нестрого меньше $b$, $a$ меньше или равно $b$ ||
| $a \geq b$ | $a$ нестрого больше $b$, $a$ больше или равно $b$ ||
| $a \ll b$ | $a$ (на)много меньше $b$ ||
| $a \gg b$ | $a$ (на)много больше $b$ ||

:::{.callout-note #nte-eqdef collapse=false title="Равенство, равенство по определению и введение обозначения"}


:::


#### Операции

| Знак, символ, запись | Значение, словесный эквивалент | Комментарии |
|:-----:|:-----|:-----|
| $a + b$ || $\sum_{i=1}^n a_i$ (см. @nte-bigop) |
| $a - b$ |||
| $a \pm b$ |||
| $a \mp b$ || $-(a\pm b) = -a \mp b$ |
| $a \cdot b$, $ab$ || $\prod_{i=1}^n a_i$ (см. @nte-bigop) |
| $\dfrac{a}{b}$ |||
| $a^p$ |||
| $\sqrt{a}$ |||
| $\sqrt[n]{a}$ |||
| $|a|$ |||
| $\floor{a}$ |||
| $\ceil{a}$ |||
| $\inta a$ | целая часть числа $a$ ||
| $\fraca a$ | дробная часть числа $a$ ||
| $\min (a,\,b)$ | минимум из двух элементов $a$ и $b$ ||
| $\max (a,\,b)$ | минимум из двух элементов $a$ и $b$ ||

:::{.callout-note #nte-bigop collapse=true title="Об обозначении «больших» символов (знаков)"}

Для сокращения записей при большом числе слагаемых, множителей и др. используются «большие» символы (знаки). Например, сумма десяти слагаемых $a_1 + a_2 + a_3 + a_4 + a_5 + a_6 + a_7 + a_8 + a_9 + a_{10}$ может быть записана с помощью *знака суммы* как $\sum_{i=1}^{10} a_i$. Здесь $i$ является индексом суммирования, которые пробегает все значения от $1$ до $10$. В общем случае (для $n$ слагаемых, множителей и др.) пишут:

- сложение: $\sum_{i=1}^{n} a_i = a_1 + a_2 + \ldots + a_n$
- умножение: $\prod_{i=1}^{n} a_i = a_1 \cdot a_2 \cdot \ldots \cdot a_n$
- пересечение (множеств): $\bigcap_{i=1}^{n} A_i = A_1 \cap A_2 \cap \ldots \cap A_n$
- объединение (множеств): $\bigcup_{i=1}^{n} A_i = A_1 \cup A_2 \cup \ldots \cup A_n$
- и др.

Если формула с «большим» знаком встречается внутри текста, то индексы обычно указываются справа от знака, как в примерах выше. Если формула вынесена из текста, то индексы обычно указываются над и под знаком --- смысл от этого не меняется:

$$
\begin{split}
\sum_{i=1}^{n} a_i = a_1 + a_2 + \ldots + a_n \\
\prod_{i=1}^{n} a_i = a_1 \cdot a_2 \cdot \ldots \cdot a_n \\
\bigcap_{i=1}^{n} A_i = A_1 \cap A_2 \cap \ldots \cap A_n \\
\bigcup_{i=1}^{n} A_i = A_1 \cup A_2 \cup \ldots \cup A_n
\end{split}
$$

Если индексы и диапазоны их значений понятны из контекста, индексы при знаке могут или вовсе опускаться --- $\sum a_i$ --- или же указываться кратко --- $\sum_i a_i$. Если в конкретном случае удобнее указать не границы изменения индекса, а множество его значений, используется запись вида $\sum_{i \in I} a_i$.

Если необходимо указать дополнительные условия на индексы, то записываются под знаком:

$$
\sum_{\substack{i,\,j\\i\neq j}} a_{ij}
$$

:::


#### Другие символы

| Знак, символ, запись | Значение, словесный эквивалент | Комментарии |
|:-----:|:-----|:-----|
| $\infty$ || $+\infty$ и $-\infty$ |





### Логика {#sec-notation-math-symbols-logic}

| Знак, символ, запись | Значение, словесный эквивалент | Комментарии |
|:-----:|:-----|:-----|
| $p$ |||
| $p \and q$ || $\andd_{i=1}^n p_i$ (см. @nte-bigop) |
| $p \or q$ || $\orr_{i=1}^n p_i$ (см. @nte-bigop) |
| $p \xor q$ |||
| $\neg p$ |||
| $p \impl q$ |||
| $p \repl q$ |||
| $p \equi q$ |||
| $\forall \, x \in A \quad p(x)$ |||
| $\exists \, x \in A \quad p(x)$ |||
| $\exists! \, x \in A \quad p(x)$ |||



### Множества {#sec-notation-math-symbols-sets}

| Знак, символ, запись | Значение, словесный эквивалент | Комментарии |
|:-----:|:-----|:-----|
| $A$ | множество $A$ ||
| $x \in A$ | элемент $x$ принадлежит множеству $A$ | элемент $x$ лежит во множестве $A$ |
| $y \notin A$ | элемент $y$ не принадлежит множеству $A$ | элемент $x$ не лежит во множестве $A$ |
| $\{x_1, x_2, \ldots, x_n\}$ | множество, заданное через перечисление элементов ||
| $\{x \in A \mid p(x)\}$ | множество, заданное через характеристическое свойство ||
| $|A|$ | мощность множества $A$ ||
| $\nothing$ | пустое множество ||
| $A = B$ | множества $A$ и $B$ равны ||
| $B \subs A$ | $B$ является подмножеством $A$ | $(B \subp A) \or (B = A)$ |
| $B \subp A$ | $B$ является собственным подмножеством $A$ ||
| $A \cap B$ | пересечение множеств $A$ и $B$ | для множеств $A_1,\, A_2, \, \ldots, \, A_n$ можно записать в виде $\bigcap_{i=1}^n A_i$ (см. @nte-bigop) |
| $A \cup B$ | объединение множеств $A$ и $B$ | для множеств $A_1,\, A_2, \, \ldots, \, A_n$ можно записать в виде $\bigcup_{i=1}^n A_i$ (см. @nte-bigop) |
| $A \sqcup B$ | дизъюнктное объединение множеств $A$ и $B$ | для множеств $A_1,\, A_2, \, \ldots, \, A_n$ можно записать в виде $\bigsqcup_{i=1}^n A_i$ (см. @nte-bigop) |
| $A \setminus B$ | разность множеств $A$ и $B$ ||
| $A \symdif B$ | симметрическая разность множеств $A$ и $B$ ||
| $(a, b)$ | упорядоченная пара элементов $a$ и $b$ ||
| $(a_1, a_2, \ldots, a_n)$ | упорядоченный набор элементов $a_1,\, a_2, \, \ldots, \, a_n$ ||
| $A \times B$ | декартово произведение множеств $A$ и $B$ | для  множеств $A_1,\, A_2, \, \ldots, \, A_n$ можно записать в виде $\prod_{i=1}^n A_i$ (см. @nte-bigop) |



### Числовые множества {#sec-notation-math-symbols-numsets}

| Знак, символ, запись | Значение, словесный эквивалент | Комментарии |
|:-----:|:-----|:-----|
| $\setN$        | множество натуральных чисел           | (см. @nte-setN) |
| $\setNo$       | множество целых неотрицательных чисел | натуральные числа, включая ноль |
| $\setZp$       | множество целых положительных чисел   | натуральные числа, исключая ноль |
| $\setZ$        | множество целых чисел                 ||
| $\setZp$       | множество целых положительных чисел   | натуральные числа, исключая ноль |
| $\setQ$        | множество рациональных чисел          ||
| $\setR$        | множество вещественных чисел          ||
| $\setC$        | множество комплексных чисел           ||
| $\intcc{a}{b}$ | отрезок $\intcc{a}{b} = \{x\in\setR \mid a \leq x \leq b\}$ | (см. @nte-intervals) |
| $\intoo{a}{b}$ | интервал $\intoo{a}{b} = \{x\in\setR \mid a < x < b\}$ | (см. @nte-intervals) |
| $\intco{a}{b}$ | полуинтервал, открытый справа $\intco{a}{b} = \{x\in\setR \mid a \leq x < b\}$ | (см. @nte-intervals) |
| $\intoc{a}{b}$ | полуинтервал, открытый слева $\intoc{a}{b} = \{x\in\setR \mid a < x \leq b\}$ | (см. @nte-intervals) |
| $\intoc{\nty}{b}$ | луч $\intoc{\nty}{b} = \{x\in\setR \mid x \leq b\}$ | (см. @nte-intervals) |
| $\intoo{\nty}{b}$ | открытый луч $\intoo{\nty}{b} = \{x\in\setR \mid x < b\}$ | (см. @nte-intervals) |
| $\intco{a}{\pty}$ | луч $\intco{a}{\pty} = \{x\in\setR \mid x \geq a\}$ | (см. @nte-intervals) |
| $\intoo{a}{\pty}$ | открытый луч $\intoo{a}{\pty} = \{x\in\setR \mid x > a\}$ | (см. @nte-intervals) |


:::{.callout-note #nte-setN collapse=true title="Об обозначении множества натуральных чисел"}

Поскольку существуют разные подходы к определению множества натуральных чисел (см. @sec-numbers-setN), в данной книге используется:

- $\setNo$ для обозначения множества натуральных чисел с нулём: $\setNo = \{0, 1, 2, 3, \ldots\}$
- $\setN$ для обозначения множества натуральных чисел, если не имеет значения, включён ноль или нет
- $\setZp$ для обозначения множества натуральных чисел без нуля, что равносильно целым положительным числам: $\setZp = \{1, 2, 3, \ldots\}$

:::

:::{.callout-note #nte-intervals collapse=true title="Об обозначении числовых промежутков"}

Существует две традиции обозначения границ числовых промежутков. Первая предполагает использование квадратных скобок для границ, включенных в промежуток, и круглых скобок для границ, не включенных в него. Так, в этой традиции отрезок будет обозначен как $[a,\,b]$, а  [открытый] интервал как $(a,\,b)$. Однако обозначение $(a,\,b)$ уже используется для:

- упорядоченной пары в теории множеств,
- координат точки на плоскости,
- формального представления комплексного числа как пары действительных чисел.

Эти объекты обладают определенными свойствами, позволяющими без существенной неоднозначности использовать для них одно и то же обозначение. Однако интервал отличается от них и представляет собой совершенно другую сущность. По этой причине и во избежание неоднозначности в книге используется вторая традиция обозначения границ числовых промежутков, согласно которой:

Хотя контекст обычно позволяет однозначно различать эти объекты, использование круглых скобок для интервалов может создать перегрузку --- разные по смыслу объекты в одном контексте обозначены одинаково. По этой причине в данной книге применяется вторая традиция, согласно которой:

- для всех типов промежутков используются только квадратные скобки;
- включение границы обозначается скобкой, направленной к числу:
    - для правой границы --- $[$, для левой --- $]$;
- исключение границы обозначается скобкой, повёрнутой от числа:
    - для правой границы --- $]$, для левой --- $[$.

Таким образом, в этой традиции отрезок будет обозначен как $\intcc{a}{b}$, а интервал как $\intoo{a}{b}$.

:::


***

### Буквы {#sec-notation-math-letters}

На всякий случай оставлю здесь таблицу с буквами и их вариантами, которые можно встретить в математике. Иногда варианты букв значительно отличаются от привычных нам, и не сразу понятно, что же это за буква. Тем не менее, в рамках книги мы всё же будем иметь дело с понятными начертаниями, поэтому этот раздел можно спокойно пропустить.

::::{.column-page-inset}
:::{.callout appearance="default" collapse=true title="Буквы и их начертания"}

**Латинский алфавит**

Буквы латинского алфавита в математических текстах могут использоваться в нескольких начертаниях, которые представлены в таблице ниже. Необходимы разные начертания для обозначения различных по своей природе объектов, так как всякого разного в математике много, а букв не много.

> Приведем некоторые примеры, чтобы понять, как применяются различные начертания одних и тех же букв на практике.
>
> - $A$ --- множество, $\mathcal A$ --- множество множеств, $\v A$ --- матрица, $\mathbb A$ --- множество алгебраических чисел;
> - $C$ --- объект, $\mathcal C$ --- категория, $\mathbb C$ --- множество комплексных чисел;
> - $d$ --- функция (метрика) расстояния, $\mathrm d$ --- дифференциал, $\mathcal D$ --- область определения функции, $\mathbb D$ --- дисперсия;
> - $X$ --- переменная (случайная величина), $x$ --- значение переменной (случайной величины), $\v x$ --- вектор значений переменной (случайной величины), $\v X$ --- матрица переменных (случайных величин)
> - $\e$ --- число Эйлера, $e$ --- ошибка модели, $\v e$ --- вектор ошибок модели, $\mathcal{E}$ --- множество значений функции, $\mathbb{E}$ --- математические ожидание

Хотя в целом за тем или иным начертанием закреплены определённые смыслы, традиции различных математических школ могут различаться, поэтому всегда не лишним будет уточнить, что обозначено той или иной буквой в том или ином начертании.

{{< include _latin-letters.qmd >}}

Вообще буква *W, w* в алфавит классической латыни не входила, так как возникла в Средневековье в алфавитах германских языков (изначально как диграф *VV*) [@bischoff1990latin]. Однако так как она входит в набор символов латиницы, зафиксированный ISO [@iso10646], она считается частью современного латинского алфавита. Справедливости ради стоит отметить, что в классической латыни отсутствовали даже *J, j* и *U, u* --- они также возникли в Средние века, отделившись от *I, i* и *V, v*, неслоговыми вариантами которых были до этого [@bischoff1990latin].

<br>
**Греческий алфавит**

Несомненно, не будет открытием, что употребляются и греческие буквы. Однако не все --- из-за совпадения начертания некоторых заглавных букв с латинскими, буквы, указанные в скобках ($[\,]$), не используются. Кроме того, из-за значительного сходства строчных вариантов латинской $V$ ($v$) и греческой $Y$ ($\upsilon$) последняя также не используется. В ряде случаев применяется полужирное начертание заглавных греческих букв. Для букв $\kappa$, $\varphi$ и $\varepsilon$ существует по два строчных варианта (второй указан в скобках $(\,)$).


{{< include _greek-letters.qmd >}}


<br>
**Другие алфавиты и буквоподобные символы**

Кроме представленного выше обилия букв --- да, их недостаточно --- используются:

- $\aleph$ --- а́леф, первая буква еврейского алфавита (для обозначения мощностей бесконечных множеств)
- $\nabla$ --- на́бла, (перевернутая $\Delta$, для обозначения градиента функции)

:::
::::
