lang: ru
language: _langs/_lang-ru.yml

metadata-files:
  - _meta/_meta-ru.yml

project:
  output-dir: _site/ru

book:
  subtitle: "Мир линейных моделей: статистика и анализ данных в R для психологов"
  author:
    - name: "Антон Ангельгардт"
      email: "anton.angelgardt@gmail.com"
  navbar:
    left:
      - text: "Книга"
        #icon: book-fill
        href: ""
      - text: "Тесты"
        #icon: check-square
        href: ""
  chapters:
    - index.qmd
    - part: chapters/ru/debug/part-debug.qmd
      chapters:
        - chapters/ru/debug/chapter-debug.qmd


format:
  html:
    cover-image: img/cover-ru.jpg
