project:
  type: book
  preview:
    port: 5050

# metadata-files:
#   - _metadata.yml


book:
  title: "WLM SDARP"
  date: today
  favicon: img/favicon.png
  navbar:
    left:
      - text: "Book"
        href: ""
      - text: "Tests"
        href: ""

bibliography: references.bib

# brand: ../shared/style/_brand.yml

crossref:
  custom:
    - key: mth
      kind: float
      reference-prefix: "Myth"
      caption-prefix: "Myth"
    - key: hst
      kind: float
      reference-prefix: "History"
      caption-prefix: "History"
    - key: prs
      kind: float
      reference-prefix: "Person"
      caption-prefix: "Person"
    - key: dts
      kind: float
      reference-prefix: "Dataset"
      caption-prefix: "Dataset"

format:
  html:
    include-in-header:
      - ../shared/includes/lvl-labels.html
    title-block-banner: img/title-block-banner.jpg
    title-block-banner-color: "#fafafa"
    toc: true
    toc-depth: 4
    # theme: ../shared/style/test.scss
    theme:
      light: [../shared/style/theme_general.scss, ../shared/style/theme_light.scss]
      dark: [../shared/style/theme_general.scss, ../shared/style/theme_dark.scss]

editor: source
