# Дизайн исследований {#appendix-research-design}

:::{.intro}
Подробное изучение дизайна исследований не является задачей данной книжки, однако поскольку мы говорим преимущественно об анализе исследовательских данных, необходимо напомнить себе, как могут быть устроены разные исследования. Это приложение не ставит собственной целью повторить курс экспериментальной психологии, но всё же основные моменты мы вспомним и положим их в контекст анализа данных.
:::

## Виды исследований {#apdx-resdes-research-types}

Статистика неразрывно связана с исследованиями, поэтому нам надо произвести некоторый рекап того, какие исследования у нас бывают. Общую классификацию исследований можно представить так (@fig-research-types):

```{mermaid}
%%| label: fig-research-types
%%| fig-cap: Способ классификации исследований
%%| fig-align: center

flowchart TD
  research(Исследования)
  theor(Теоретические)
  empir(Эмпирические)
  cab(Кабинетные)
  qual(Качественные)
  quan(Количественные)
  meta(Мета-анализы)
  exp(Экспериментальные)
  nonexp("Доэкспериментальные
          Квазиэспериментальные
          Корреляционные")
  
  research --> theor
  research --> empir
  theor -.-> cab
  empir -.-> cab
  empir --> qual
  empir --> quan
  quan --> nonexp
  quan --> exp
  quan --> meta
```


## Критерии причинности {#apdx-resdes-causal-inference}

John Stuart Mill

Причинно-следственная связь X → Y имеет место при выполнении трёх условий:

* наличие статистически значимой связи --- есть корреляция между X и Y
* предшествование во времени --- X предшествует Y
* отсутствие третьих переменных --- наблюдаемая связь между X и Y не может быть объяснена никакими иными причинами

:::{#tbl-causal-experiment}

|Критерий причинности|Логика эксперимента|
|:---:|:---:|
|Причина предшествует во времени следствию|Создаём причины и наблюдаем следствия|
|Причина связана со следствием|Проверяем, связан ли разброс в причинах по условиям с разбросом следствий|
|Отсутствуют альтернативные объяснения следствия, кроме причины|Осуществляем экспериментальный контроль [побочных переменных]|

Причинность в эксперименте
:::

## Валидность исследования (эксперимента?) {#apdx-resdes-valid}

* Конструктная валидность --- верная ли идея эксперимента, верно ли выбраны процедуры воздействия
* Операциональная валидность --- критерий оценки проведенного исследования с точки зрения соответствия использованных в исследовании методик задания и измерения переменных эмпирически нагруженными понятиям НП, ЗП и ПП.
* Внутренняя валидность --- хорошо ли эксперимент спланирован, приближается ли к идеальному
* Статистическая валидность --- верно ли отражают данные статистики наличие экспериментального эффетка
* Внешнняя валидность --- можно ли перенести эти результаты на реальные ситуации, другие выборки, материал, способы измерения зависимых переменных


### Угрозы валидности исследования {#apdx-resdes-valid-threats}

Д. Кэмпбелл

#### Угрозы внутренней валидность {#apdx-resdes-valid-threats-internal}


* Эффект истории (фона) --- события между воздействием и измерением
* Эффект созревания (естественного развития) --- испытуемые со временем развиваются
* Эффект тестирования --- первое измерение влияет на результаты последующих
* Погрешность измерения зависимой переменной
* Регрессия к среднему --- группы, отобранные как контрастные по какому-либо показателю, при повторном измерении покажут результат более близкий к среднему
* Неэквивалентность групп --- в силу индивидуальных различий группы испытуемых изначально различаются
* Эффект отсева или вымирания --- со временем часть испытуемых выбывает из исследования
* Взаимодействие перечисленных факторов


#### Угрозы внешней валидность {#apdx-resdes-valid-threats-external}

* Влияние тестирования --- результаты эксперимента будут применимы лишь к людям, которые были протестированы
* Взаимодействие отбора и экспериментального воздействия ---- результаты применимы лишь к людям с определенными характеристиками
* Условия организации эксперимента определяют реакцию испытуемых на эксперимент --- результаты применимы лишь к людям в определенных условиях
* Взаимная интерференция (взаимовлияние) экспериментальных воздействия, если их несколько --- результаты будут применимы лишь к людям, на которых воздействовали именно так (в таком порядке…)


## Эксперимент {#apdx-resdes-experiment}

Эксперимент --- метод исследования, в котором реализуется специально организованное контролируемое воздействие на объект с целью проверки каузальных гипотез.

Виды экспериментов

* По цели
    * поисковый
    * подтверждающий
    * критический
* По условиям
    * лабораторный
    * внелабораторный
    * «естественный»
* По осуществлению
    * реальный
    * идеальный
    * мысленный

### Идеальный эксперимент {#apdx-resdes-experiment-ideal}

Различия между экспериментальными условиями **только по уровням зависимой переменной**

* нет индивидуальных различий --- все испытуемые одинаковы
* испытуемые и внешние условия неизменны во времени --- времени нет
* нет ограничений по выборке и количеству воздействий --- эксперимент бесконечный

Идеальный эксперимент **абсолютно валиден**, но невозможен. Однако он служит «точкой отсчёта» для оценки степени валидности реального эксперимента.

### Переменные в эксперименте

* Независимая переменная (НП, independent variable, IV) --- фактор, который, согласно гипотезе, влияет на показатели зависимой переменной.

* Зависимая переменная (ЗП, dependent variable, DV) -- отклик, предположительно, вызываемый изменением независимой переменной.

* Побочная переменная (ПП) --- переменная, которая не входит в экспериментальную гипотезу, но в условиях эксперимента может либо повлиять на изучаемый базисный процесс, либо смешиваться с независимой переменной, что исказит (нарушит) исследуемую зависимость.

* Дополнительная переменная (ДП) --- составляющая часть экспериментальной гипотезы, имеющей частный характер, ограничивающая широту обобщения об устанавливаемой зависимости.


### Экспериментальные планы {#apdx-resdes-expdes}

Экспериментальный план --- способ организовать эксперимент так, чтобы исключить возможность альтернативных объяснений, подрывающих внутреннюю валидность.

#### Нотация по Д. Кэмпбеллу {#apdx-resdes-expdes-notation}

* R --- рандомизация (randomization)
* O --- измерение (observation) зависимой переменной
* X --- воздействие (наличие) независимой переменной

#### Планы для одной независимой переменной {#apdx-resdes-expdes-1iv}

##### Дизайн с одним испытуемым

##### Межгрупповой план

between-subject design

* Включают несколько групп испытуемых
* Основная угроза валидность --- индивидуальные различия → неэквивалентность групп (разные уровни НП в неодинаковых условиях → смешение)
* Стратегии формирования эквивалентных групп:
    * рандомизация
    * попарный отбор (matching) --- сортируем людей по важному свойству на эквивалетные пары и случайно назначаем одного из каждой пары в ту или иную группу
    * стратометрический отбор --- подбираем испытуемых в группы так, чтобы уравнять их по полу, возрасту и т.д.


* План с предварительным и итоговым тестирование и контрольной группой

$$
\begin{align}
& R \quad O \quad X \quad O \\
& R \quad O \quad \quad \quad O
\end{align}
$$

* План Соломона для четырёх групп

$$
\begin{align}
& R \quad O \quad X \quad O \\
& R \quad O \quad \quad \quad O \\
& R \quad \quad \quad X \quad O \\
& R \quad \quad \quad \quad \quad O \\
\end{align}
$$

* План с контрольной группой и тестированием только после воздействия

$$
\begin{align}
& R \quad X \quad O \\
& R \quad \quad \quad O
\end{align}
$$

:::{.callout-tip}
###### Претест: pro et contra

Данные претеста позволяют оценить **эффект вымирания**

* отличаются ли испытуемые, которые вышли из исследования от тех, кто остался до конца?
* отличаются ли испытуемые, которые вышли из разных экспериментальных условий (например, экспериментальной и контрольной группы?)

Если да, то можно контролировать этот эффект, подбирая эквивалентные группы из выборки.

Претест повышает статистическую мощность анализа → выше шансы получить результат

Проблема эффекта тестирования --- испытуемые, которые прошли тест, могут иначе реагировать на экспериментальное воздействие
:::

##### Внутригрупповой план

within-subject design

* Включают одну группу испытуемых
* Основные угрозы валидности:
    * позиционные эффекта --- стимулы на разных позициях в ряду → неодинаковые условия для разных уровней НП → смешение
    * эффект последовательности --- похожие или контрастные стимулы идут подряд → эффекты установки / прайминга → смешение
* Контроль эффектов:
    * рандомизация последовательности стимулов для каждого испытуемого
    * позиционное уравнивание --- стимулы разных типов, в среднем, на одной и той же позиции
    * балансировка --- стимулы одного типа не идут подряд
    * контрбалансировка (реверсивное уравнивание ??) --- делим группу случайным образом на две подгруппы, одной даём стимулы в порядке BA, другой --- AB.


* Интраиндивидуальный план --- все уровни НП предъявляются разными испытуемым в одной и той же последовательности.
* Кроссиндивидуальный план --- разным испытуемым предъявляется разная последовательность уровней НП.


#### Факторные планы




## Корреляционные исследования

## Доэкспериментальные планы

* Исследование единичного случая

$$
X \quad O
$$

* План с предварительным и итоговым тестированием на одной группе

$$
O \quad X \quad O
$$

* Сравнение статических групп

$$
\begin{align}
X \quad O \\
\hdashline
\quad O
\end{align}
$$


