# Числа {#appendix-numbers}

{{< include other/_symbols.qmd >}}

:::{.intro}

Большая часть этого приложения либо очевидна, либо интуитивна, либо вам, вероятно, хорошо знакома из курса школьной математики. Тем не менее, для соблюдения некой строгости изложения, даже очевидные вещи здесь формально изложены.

* Если вы хорошо управляетесь со всеми числами, пропустите это приложение.
* Если вы хорошо управляете со всеми числами, кроме комплексных, прыгайте [сюда](#appendix-numbers-c).
* Если вы не уверены в том, что хорошо управляетесь с числами --- приглашаю к математическому чтиву.

:::



Если мы попытаемся выяснить, что такое число, то потерпим решительное фиаско. Обратившись к математическому словарю [@math-enc, с. 873] мы обнаружим следующее:

> Число --- основное понятие математики, сложившееся в ходе длительного исторического развития. Возникновение и формирование этого понятия происходило вместе с зарождением математики. Практическая деятельность человека, с одной стороны, и внутренние потребности математики --- с другой определили развитие понятия числа.

Очень точно и понятно, спасибо. Однако что тут удивляться --- число, действительно, основное понятие математики, а с определением собственных основных понятий у наук часто бывают существенные затруднения. Ровно в такой же ситуации мы оказываемся, например, с «точкой» в геометрии. По идее, задача определения фундаментальных понятий адресуется философии, как дисциплине осмысляющей всё и вся, но тут нас тоже не то чтобы ждёт что-то уверенно определенное [@philos-enc]:

> Число --- абстрактное, лишенное особенного содержания обозначение какого-либо члена некоторого ряда, в котором этому члену предшествует или следует за ним какой-нибудь другой определенный член; абстрактный индивидуальный признак, отличающий одно множество от другого того же рода.

Весьма философски...

В общем, приходится признать, что мы не знаем, что такое числа, но при этом неплохо интуитивно понимаем, как они работают (по крайне мере, определенные из них). Далее мы попытаемся проследить, как развивалось понятие числа исходя из внутренних потребностей математики, а если вас заинтересует развитие чисел в историческом контексте, то про это написана книга в 600 страниц «The universal history of numbers» [@ifrah2000].





## Натуральные числа {#appendix-numbers-n}

Первыми исторически возникли натуральные числа, чтобы можно было считать окружающие предметы. Сама идея числа и счёта возникла далеко не сразу --- закономерности восприятия позволяют выяснить, что некоторое множество объектов изменилось (объект пропал или появился) и без вовлечения процедуры счёта [@history-of-numbers]. Тем не менее, в определенные момент всё же возникает необходимость считать предметы и формируется некоторое абстрактное представление о *натуральных числах как тех, которые используются при счёте предметов*.

Сегодня по прошествии многих веков с момента «рождения» чисел мы пользуемся для их записи арабскими (они же индийские, они же индо-арабские[^term-digit]) цифрами и десятичной [системой счисления](appendix-numbers-iron.qmd#appendix-numbers-num-systems):

$$
0 \quad 1 \quad 2 \quad 3 \quad 4 \quad 5 \quad 6 \quad 7 \quad 8 \quad 9
$$

[^term-digit]: Термины «арабские цифры (аrabic digits)» и «индийские цифры (hindi digits)» в современном мире [неоднозначны](https://www.unicode.org/terminology/digits.html), так как цифры, используемые сегодня в арабских странах и Индии, отличаются от тех, которые называются арабскими на территории европейских стран.



### Ноль как натуральное число {#appendix-numbers-n-zero}

К нулю как натуральному числу относятся по-разному. Представление о натуральных числах как используются при счете предметов допускает две трактовки:

* если мы рассматриваем натуральные числа как использующие собственно при счете предметов, то ноль в натуральные числа не входит (*первый кофе*, *второй кофе*, *третий кофе*, ...);
* если мы рассматриваем натуральные числа как возникающие при обозначении количества предметов, то ноль входит в натуральные числа (*ноль скриптов*, *один скрипт*, *два скрипта*, ...).

В силу такого положения дел в математике введено два обозначения [@iso80000-2-2019]:

* $\setN = \{0, 1, 2, 3, \ldots \}$
* $\setNstar = \{ 1, 2, 3, \ldots\}$

Оба в книге используются соответствующим образом.



### Операции над натуральными числами {#appendix-numbers-n-oprations}

Над натуральными числами определены следующие операции ($a, b \in \setN$):

* сложение ($a + b$)
* умножение ($a \cdot b$)
* возведение в степень ($a ^ b$)
* вычитание ($a - b, \, a \geq b$)
* деление с остатком ($a \div b = (q, r), \, a = q \cdot b + r, \, r < b$)

Операции сложения, умножения и возведения в степень являются **замкнутыми**, то есть не выводят результат из множества $\setN$. Действительно,

* какие бы два натуральных числа мы ни складывали друг с другом, результат всегда будет натуральным числом: $\forall a, b \in \setN \; (a + b) \in \setN$
* какие бы два натуральных числа мы ни умножали друг на друга, результат всегда будет натуральным числом: $\forall a, b \in \setN \; (a \cdot b) \in \setN$
* в какую бы натуральную степень мы ни возводили натуральные число, результат всегда будет натуральным числом: $\forall a, b \in \setN \; a^b \in \setN$

Операции вычитания и деления в остатком в общем случае **не являются замкнутыми**, поскольку определены не для всех натуральных чисел. В частности,

* вычитание $a - b$ определено только в случае[^minus_nstar], когда $a \geq b$, так как

$$
\begin{split}
\forall a, b \in \setN, a \geq b \; (a - b) \in \setN \\
\forall a, b \in \setN, a < b \; (a - b) \notin \setN \\
\end{split}
$$

* *деление на ноль невозможно*, так как во множестве натуральных чисел не существует $r < 0$, а по определению деления с остатков мы должны получить в остатке число, меньшее делителя.

[^minus_nstar]: Только в случае $a > b$, если $a, b \in \setNstar$.


### Аксиомы Пеано {#appendix-numbers-n-peano}

Хотя всё в натуральных числах вроде бы весьма очевидно и даже «осязаемо», с развитием математики, а в особенности теории множеств, возникла необходимость поставить натуральные числа на формальные основания. Этим занялся итальяснкий математик [Джузеппе Пеано](https://mathshistory.st-andrews.ac.uk/Biographies/Peano/), сформулировав систему аксиом для натуральных чисел.

Рассмотрим множество натуральных чисел $\setNstar$, единицу $1$ (как особо выделенный элемент) и функцию $S(n) = n'$, сопоставляющую некоторому числу $n$ следующее за ним число $n'$ --- функцию следования (successor function). Тогда система аксиом примет следующий вид[^peano-axioms]:

[^peano-axioms]: Изначально самим Дж. Пеано было введено девять аксиом [@peano1889]. Cовременный вариант аксиом Пеано для $\setNstar$ состоит из пяти аксиом [@kumar-peano]. Здесь представлен вариант аксиом для $\setN$ [@pelayo-peano].

1. $0$ является натуральным числом;

$$
0 \in \setN
$${#eq-peano1}

2. За каждым натуральным числом следует натуральное число;

$$
n \in \setN \Rightarrow S(n) \in \setN
$${#eq-peano2}

3. $0$ не следует ни за каким натуральным числом;

$$
\nexists \, n \in \setN : S(n) = 0
$${#eq-peano3}

4. Если натуральное число $a$ непосредственно следует как за числом $b$, так и за числом $c$, то $b$ и $c$ являются одним и тем же числом;

$$
\big( S(b) = a \wedge S(c) = a \big) \Rightarrow b = c
$${#eq-peano4}

5. [Аксиома индукции] Если какое-либо предположение доказано для $0$ (база индукции) и если из допущения, что оно верно для натурального числа $n$, следует, что оно верно для следующего за $n$ натурального числа (шаг индукции, индукционный переход), то это предположение верно для всех натуральных чисел.

$$
P(0) \wedge \forall n \Big( P(n) \Rightarrow P\big( S(n) \big) \Big) \Rightarrow \forall n \in \setN \; P(n)
$${#eq-peano5}



### Формализация арифметики {#appendix-numbers-n-peano}

Используя функцию следования, вводимую в рамках аксиом Пеано, можно формализовать всю арифметику, введя следующие аксиомы сложения и умножения [@pelayo-peano]:

$$
\begin{split}
& n + 0 = n \\
& n_1 + S(n_2) = S(n_1 + n_2) \\
& n \cdot 0 = 0 \\
& n_1 \cdot S(n_2) = n_1 + n_1 \cdot n_2
\end{split}
$${#eq-arithm-axioms}

#### Сложение натуральных чисел {#appendix-numbers-n-sum}

Пусть мы хотим вычислить $1 + 1$. Обозначим второе слагаемое как $1 = S(0)$. Тогда

$$
1 + 1 = 1 + S(0) = S(1 + 0) = S(1) = 2
$$

Аналогично,

$$
1 + 2 = 1 + S(1) = S(1 + 1) = S(2) = 3
$$

Повторив эту операцию столько раз, сколько требуется для сложения конкретны чисел, мы получим хорошо знакомое нам сложение, которым практически от рождения пользуемся.


#### Умножение натуральных чисел {#appendix-numbers-n-prod}

Здесь, во-первых, мы можем получить хорошо знакомый нам факт, что $n \cdot 1 = n$:

$$
n \cdot 1 = n \cdot S(0) = n + n \cdot 0 = n + 0 = n
$$
А если нам необходимо получить произведение двух чисел, то действуем так:

$$
2 \cdot 2 = 2 \cdot S(1) = 2 + 2 \cdot 1 = 2 + 2 = 4
$$



### Определение операций друг через друга

Сами операции определяются друг через друга:

* $a + b = a + \underbrace{1 + 1 + \ldots + 1}_b$
* $a \cdot b = \underbrace{a + a + \ldots + a}_b$
* $a^b = \underbrace{a \cdot a \cdot \ldots \cdot a}_b$



### Сумма $n$ натуральных чисел {#appendix-numbers-n-sum-n-natural}

::: {#prp-sum-n-natural}
Сумма $n$ натуральных чисел $S_n$ равна $\displaystyle \frac{n \cdot (n+1)}{2}$.
:::

:::{.proof}
Докажем @prp-sum-n-natural по индукции. Будем рассматривать множество натуральных чисел $\setN$, где первым элементов является $0$.

Сформулируем **базу индукции**:

$$
n = 0, \quad S_0 = 0
$$

Согласно доказываемому утверждению,

$$
S_0 = \frac{0 \cdot (0 + 1)}{2}
$$

Очевидно, что база индукции справелива:

$$
S_0 = \frac{0 \cdot (0+1)}{2} = \frac{0 \cdot 1}{2} = \frac{0}{2} = 0
$$

> В качестве упражнения можно рассмотреть и несколько последующих случаев, однако с точки зрения доказательства это избыточно:

$$
\begin{split}
n = 1, &\quad S_1 = S_0 + 1 = 0 + 1 = 1, \quad S_1 = \frac{1 \cdot (1+1)}{2} = \frac{1 \cdot 2}{2} = 1 \\
n = 2, &\quad S_2 =S_1 + 2 = 0 + 1 + 2 = 3, \quad S_2 = \frac{2 \cdot (2+1)}{2} = \frac{2 \cdot 3}{2} = 3
\end{split}
$${#eq-sum-n-natural-12}

Итак, для первого $n = 0$ (в нашем случае также для нескольких других первых $n$) утверждение выполнено. Если мы теперь докажем, что утверждение выполнено для $n+1$, то есть совершим **индукционный переход**, то доказательно будет завершено.

Предположим, что для $n$ утверждение верно. Тогда для $n+1$, с одной стороны (ср. с @eq-sum-n-natural-12),

$$
S_{n+1} = S_n + (n +1)
$$

С другой стороны, согласно доказываемому утверждению

$$
S_{n+1} = \frac{(n+1)(n+1+1)}{2} = \frac{(n+1)(n+2)}{2}
$$

Получается, что

$$
\begin{split}
S_{n+1} &= S_n + (n +1) = \\
& = \frac{n(n+1)}{2} + (n+1) = \frac{n(n+1)}{2} + \frac{2(n+1)}{2} = \\
& = \frac{n(n+1)+2(n+1)}{2} = \frac{(n+1)(n+2)}{2}
\end{split}
$$

Утверждение доказано.

:::


## Целые числа {#appendix-numbers-z}

При попытке замкнуть множество натуральных чисел относительно вычитания возникает его расширение --- множество целых чисел, обозначаемое $\setZ$:

$$
\setZ = \setN \cup \{-1, \, -2, \, -3, \, \ldots \} = \setNstar \cup \{0\} \cup \{-1, \, -2, \, -3, \, \ldots \}
$$

Во множестве целых чисел справедливо, что для каждого числа $n$ из этого множества найдется такое число $-n$ из этого же множества, что их сумма будет равна нулю:

$$
\forall n \in \setZ \, \exists -\!n \in \setZ : n + (-n) = 0
$$

Число $-n$ называется *противоположным* числу $n$. Поскольку сложно возразить утверждению $0 + 0 = 0$, то $0$ является противоположным самому себе.





## Рациональные числа {#appendix-numbers-q}

Хотелось бы замкнуть множество целых чисел ещё и относительно операции деления, чтобы все было окончательно красиво --- это приводит к его расширению до множества рациональных чисел $\setQ$. Это множество задается следующим образом:

$$
\setQ = \left\{ \frac{m}{n},  \, m \in \setZ, \, n \in \setNstar \right\}
$$







## Вещественные числа {#appendix-numbers-r}

Рациональных чисел оказывается недостаточно, чтобы описать все существующие феномены. В частности, широко известен пример вычисления гипотенузы равнобедренного прямоугольного треугольника с катетом, равным $1$.

$\setR$

$\setI = \setR \setminus \setQ$





## Комплексные числа {#appendix-numbers-c}

Можно было бы спокойно жить с вещественными числами, если бы не уравнения вида

$$
x^2 + 1 = 0
$${#eq-x2-eq-minus-one}

Если мы начнем его решать, что получим следующее:

$$
\begin{split}
x^2 + 1 &= 0 \\
x^2 &= -1 \\
\end{split}
$$

Можно было бы остановиться и сказать, что это чушь и такого не бывает. Но такой ответ математиков не устраивает, и они продолжают:

$$
\begin{split}
x^2 &= -1 \\
x_1 &= \sqrt{-1} \\
x_2 &= -\sqrt{-1}
\end{split}
$$

Штош, допустим. Попробуем решить следующее уравнение:

$$
x^2 + 3 = -6
$${#eq-x2-eq-minus-four}

По той же схеме,

$$
\begin{split}
x^2 - 2 &= -6 \\
x^2 &= -4 \\
x &= \pm \sqrt{-4} \\
x &= \pm \sqrt{(-1) \cdot 4} \\
x &= \pm \sqrt{-1} \cdot \sqrt{4} \\
x &= \pm \sqrt{-1} \cdot 2
\end{split}
$$

Интересная ситуация выходит: уже второй раз нам попадается $\sqrt{-1}$, а как известно, под знаком квадратного корня может стоять только положительное число[^arithm-sqrt]. Чтобы решить эту неприятность, математики ввели новое число $i$ --- **мнимую единицу**. Она обладает интересным свойством:

[^arithm-sqrt]: Здесь мы говорим об арифметическом квадратном корне.

$$
i^2 = -1
$${#eq-i-sq-equals-minus-one}

Введение мнимой единицы позволяет записать решения рассмотренных выше уравнений в более «приличном» виде, где отсутствует извлечение корня из отрицательного числа. В первом случае (@eq-x2-eq-minus-one):

$$
\begin{split}
x^2 + 1 &= 0 \\
x^2 &= -1 \\
x_1 &= \sqrt{-1} = \sqrt{i^2} = i \\
x_2 &= -\sqrt{-1} = -\sqrt{i^2} = -i
\end{split}
$$

Во втором случае (@eq-x2-eq-minus-four):

$$
\begin{split}
x^2 - 2 &= -6 \\
x^2 &= -4 \\
x &= \pm \sqrt{-4} \\
x &= \pm \sqrt{(-1) \cdot 4} \\
x &= \pm \sqrt{i^2 \cdot 4} \\
x &= \pm \sqrt{4} \cdot i \\
x_1 &= 2i \\
x_2 &= -2i \\
\end{split}
$$

Кроме того, мнимая единица даёт возможность расширить поле вещественных чисел до поля комплексных $\setC$:

$$
\setC = \{ a + bi, \, a, b \in \setR \}
$$


:::{.callout-important #sqrti-error}
###### $i \neq \sqrt{-1}$???

Если присмотреться к мнимой единице внимательно, то можно обнаружить следующее:

$$
\begin{split}
i^2 &= -1 \\
\sqrt{i^2} &= \sqrt{-1} \\
i &= \sqrt{-1}
\end{split}
$$

Но последнее не совсем верно.

Вроде мы математически все справедливо, однако обозначения $i$ и $\sqrt{-1}$ не вполне эквивалентны.

Так, если мы воспользуемся свойством квадратного корня, то можем получить следующее *некорректное* рассуждение:

$$
i^2 = (\sqrt{-1})^2 = \sqrt{-1} \cdot \sqrt{-1} = \sqrt{(-1) \cdot (-1)} = \sqrt{1} = 1
$$

Аналогично, например, можно получить, что

$$
(\sqrt{-2})^2 = \sqrt{-2} \cdot \sqrt{-2} = \sqrt{(-2) \cdot (-2)} = \sqrt{4} = 2
$${#eq-sqrt-minus-two-sq-error}

Возникает оно потому, что значение корня из отрицательного числа определено неоднозначно. В современной математической литературе принято во избежании ошибок выражения с квадратными корнями из отрицательных чисел записываются сразу с выделением мнимой единицы --- $i\sqrt{2}$:

$$
\sqrt{-2} = \sqrt{(-1) \cdot 2} = \sqrt{2i^2} = i\sqrt{2}
$$

В таком случае ошибок, подобных примеру c $(\sqrt{-2})^2$ (@eq-sqrt-minus-two-sq-error) не возникает:

$$
(i\sqrt{2})^2 = i^2 \cdot (\sqrt{2})^2 = -2
$$

Собственно, именно поэтому мнимую единицу определяют через её квадрат (@eq-i-sq-equals-minus-one), а не через её равенство $\sqrt{-1}$.
:::


КОМПЛЕКСНАЯ ПЛОСКОСТЬ

Сопряженное число

точно ли для любого?

$$
\forall z \in \setC, \, z = a + bi \,\, \exists \bar z = a - bi
$$

$$
z \cdot \bar z = (a + bi)(a - bi) = a^2 - abi + abi - b^2i^2 = a^2 + b^2
$$


Сложение и вычитание:

$$
z_1 + z_2 = (a_1 + b_1 i) + (a_2 + b_2 i) = (a_1 + a_2) + (b_1 + b_2)i
$$

$$
z_1 - z_2 = (a_1 + b_1 i) - (a_2 + b_2 i) = (a_1 - a_2) + (b_1 - b_2)i
$$

Для любых $u, v, w \in \setC$ выполняются следующие свойства:

$$
\begin{split}
u + v = v + u \\
u + (v + w) = (u + v) + w \\
u + 0 = u \\
u + (-u) = 0 \\
u - v = u + (-v)
\end{split}
$$

Умножение:

$$
\begin{split}
z_1 \cdot z_2 & = \\
& = (a_1 + b_1 i) \cdot (a_2 + b_2 i) = a_1 a_2 + a_1 b_2i + a_2 b_1i + b_1 b_2 i^2 = \\
& = (a_1 a_2 + b_1 b_2 i^2) + (a_1 b_2 i + a_2 b_1 i) = \\
& = (a_1 a_2 - b_1 b_2) + (a_1 b_2 + a_2 b_1)i
\end{split}
$$


$$
\begin{split}
u \cdot v = v \cdot u \\
u \cdot (v \cdot w) = (u \cdot v) \cdot w \\
u \cdot 1 = u \\
u \cdot 0 = 0 \\
u \cdot (v + w) = (u \cdot v) + (u \cdot w)
\end{split}
$$


Деление:

$$
\frac{1}{z} = \frac{1}{a + bi} = \frac{(a - bi)}{(a + bi) (a - bi)} = \frac{a - bi}{a^2 + b^2} = \frac{a}{a^2 + b^2} + \frac{b}{a^2 + b^2}i
$$

$$
\frac{z_1}{z_2} = \frac{a_1 + b_1 i}{a_2 + b_2 i} = \frac{(a_1 + b_1 i)(a_2 - b_2 i)}{(a_2 + b_2 i)(a_2 - b_2 i)} = \frac{a_1 a_2 + b_1 b_2}{a_2^2 + b_2^2} + \frac{a_2 b_1 - a_1 b_2}{a_2^2 + b_2^2}i
$$




