# Теория множеств {#math-settheory}

{{< include other/_symbols.qmd >}}

```{r opts, echo=FALSE, eval=TRUE, message=FALSE, warning=FALSE, error=FALSE}
knitr::opts_chunk$set(echo=TRUE, eval=TRUE, message=FALSE, warning=FALSE, error=FALSE)
```

:::{.intro}
Вступление
:::

## Множества и подмножества

## Мощность множества


### Бесконечности

:::{.lab-guru}
:::

Действительно ли существуют несчётные бесконечные множества? Иначе говоря, действительно ли существуют множества, мощность которых превосходит мощность множества натуральных чисел? Иными словами, действительно ли существуют множества, элементы которых нельзя пронумеровать?

Рассмотрим множество бесконечных последовательностей из нулей и единиц. Для наглядности можно выписать несколько элементов такого множества:

$$
\begin{Bmatrix}
0 & 1 & 1 & 1 & 1 & 0 & 0 & 0 & 0 & 1 & 1 &\ldots \\
1 & 0 & 0 & 0 & 1 & 1 & 1 & 0 & 0 & 1 & 1 & \ldots \\
0 & 0 & 0 & 1 & 1 & 1 & 0 & 0 & 1 & 1 & 0 & \ldots \\
1 & 1 & 0 & 1 & 1 & 0 & 1 & 1 & 0 & 1 & 1 & \ldots \\
1 & 0 & 1 & 0 & 1 & 0 & 1 & 0 & 1 & 1 & 0 & \ldots \\
&&&&&\vdots&&&& \\
0 & 1 & 0 & 1 & 0 & 1 & 0 & 1 & 0 & 0 & 1 & \ldots \\
1 & 1 & 1 & 1 & 1 & 0 & 0 & 0 & 0 & 0 & 0 & \ldots \\
&&&&&\vdots&&&&
\end{Bmatrix}
$$

Предположим мы потратили бесконечное время и выписали все возможные такие последовательности. Пронумеруем их:

$$
\begin{Bmatrix}
\circled{1} & 0 & 1 & 1 & 1 & 1 & 0 & 0 & 0 & 0 & 1 & 1 &\ldots \\
\circled{2} & 1 & 0 & 0 & 0 & 1 & 1 & 1 & 0 & 0 & 1 & 1 & \ldots \\
\circled{3} & 0 & 0 & 0 & 1 & 1 & 1 & 0 & 0 & 1 & 1 & 0 & \ldots \\
\circled{4} & 1 & 1 & 0 & 1 & 1 & 0 & 1 & 1 & 0 & 1 & 1 & \ldots \\
\circled{5} & 1 & 0 & 1 & 0 & 1 & 0 & 1 & 0 & 1 & 1 & 0 & \ldots \\
& &&&&&\vdots&&&& \\
\circled{n} & 0 & 1 & 0 & 1 & 0 & 1 & 0 & 1 & 0 & 0 & 1 & \ldots \\
\circled{n+1} & 1 & 1 & 1 & 1 & 1 & 0 & 0 & 0 & 0 & 0 & 0 & \ldots \\
&&&&&\vdots&&&&
\end{Bmatrix}
$$

Мы предъявили биекцию между множеством натуральных чисел и построенным нами множеством бесконечных последовательностей из нулей и единиц. Если учесть, что мы выписали множество всех возможгых последовательностей, то получается, что построенное множество счётно?

Не совсем --- мы забыли выписать одну последовательность. 

$$
\begin{Bmatrix}
\circled{1} & \boxed 0 & 1 & 1 & 1 & 1 & 0 & 0 & 0 & \ldots & 1 & 1 & \ldots \\
\circled{2} & 1 & \boxed 0 & 0 & 0 & 1 & 1 & 1 & 0 & \ldots & 1 & 1 & \ldots \\
\circled{3} & 0 & 0 & \boxed 0 & 1 & 1 & 1 & 0 & 0 & \ldots & 1 & 0 & \ldots \\
\circled{4} & 1 & 1 & 0 & \boxed 1 & 1 & 0 & 1 & 1 & \ldots & 1 & 1 & \ldots \\
\circled{5} & 1 & 0 & 1 & 0 & \boxed 1 & 0 & 1 & 0 & \dots & 1 & 0 & \ldots \\
& &&&&&\vdots&&&& \\
\circled{n} & 0 & 1 & 0 & 1 & 0 & 1 & 0 & 1 & \dots & \boxed 0 & 1 & \ldots \\
\circled{n+1} & 1 & 1 & 1 & 1 & 1 & 0 & 0 & 0 & \ldots & 0 & \boxed 0 & \ldots \\
&&&&&\vdots&&&&
\end{Bmatrix}
$$

$$
\begin{matrix}
\boxed 1 & \boxed 1 & \boxed 1 & \boxed 0 & \boxed 0 & 0 & 0 & 0 & \ldots & \boxed 1 & \boxed 1 & \ldots
\end{matrix}
$$





## Операции над множествами {}

:::{#prp-intersection-commutative}
$$
A \cap B = B \cap A
$$
:::

:::{.proof}
$$
\begin{split}
A \cap B & \defin{=} \{a \mid a \in A \and a \in B\} \\
B \cap A & \defin{=} \{a \mid a \in B \and a \in A\}
\end{split}
$$

Согласно коммутативности конъюнкции (@prp-and-commutative), высказывания $a \in A \and a \in B$ и $a \in B \and a \in A$ равносильны, следовательно множество $B \cap A$ может быть задано как $\{a \mid a \in A \and a \in B\}$, из чего следует, что множества $A \cap B$ и $B \cap A$ совпадают, следовательно, они равны.

:::



:::{#prp-union-commutative}
$$
A \cup B = B \cup A
$$
:::


:::{#prp-intersection-associative}

$$
A \cap (B \cap C) = (A \cap B) \cap C
$$
:::

:::{#prp-union-associative}
$$
A \cup (B \cup C) = (A \cup B) \cup C
$$
:::

:::{#prp-intersection-distributive}
$$
A \cup (B \cap C) = (A \cup B) \cap (B \cup C)
$$
:::

:::{#prp-union-distributive}
$$
A \cap (B \cup C) = (A \cap B) \cup (B \cap C)
$$
:::

:::{#prp-intersection-demorgan}
$$
A \setminus (B \cap C) = (A \setminus B) \cup (A \setminus C)
$$
:::

:::{#prp-union-demorgan}
$$
A \setminus (B \cup C) = (A \setminus B) \cap (A \setminus C)
$$
:::


```{=html}
<script type="text/javascript" src="./js/chapter.js"></script>
```
