# Математика для анализа данных {#part-math}

:::{.intro}
В этой части мы познакомимся с основами математики, которые нам будут необходимы для погружения в статистику и анализ данных.
:::

## Почему стоит изучать математику?

Во-первых, потому что это красиво (@fig-math-fractals и @fig-math-pi-irrational-vid).

:::{#fig-math-fractals}

{{< video https://youtu.be/RdZVPQ2cZ74?si=Z2kyOg9o0fNIzDrV >}}

Curlicue Fractals by Chirag Dudhat
:::

:::{#fig-math-pi-irrational-vid}

{{< video https://youtu.be/tuR5NI-bvu8?si=J4vhaPsofTSYb8ST >}}

π painting “The area of a Circle” ENDLESSLY by Chirag Dudhat
:::

Во-вторых, потому что в математике происходит дикий экшон (@fig-math-anim-vs-math).

:::{#fig-math-anim-vs-math}

{{< video https://youtu.be/B1J6Ou4q8vE?si=SiH-rTuqGtTM6ssa >}}

Animation vs Math by Alan Becker Team[^anim-vs-physics]
:::

[^anim-vs-physics]: Для впечатлившихся: от команды Алана есть ещё аналогичный [видос про физику](https://youtu.be/ErMSHiQRnc8?si=I14AAXK_4Ypwe6do). Там не всё полностью корректно, но с учетом художественных допущений произведение крайне достойное!

Ну, а в-третьих, почему-то так складывается, что математика крайне удачно подходит[^math-forth] в качестве инструмента для описания наблюдаемых явлений, в том числе того, что мы наблюдаем в наших исследованиях --- и научных, и индустриальных. К тому же, статистика, на которой стоят все методы анализа данных, является разделом математики, так что ситуация весьма понятная --- придется погрузиться в этот дивный мир.

[^math-forth]: На тему описания мира через математику хорошо повествует [А. М. Семихатов](https://ru.wikipedia.org/wiki/%D0%A1%D0%B5%D0%BC%D0%B8%D1%85%D0%B0%D1%82%D0%BE%D0%B2,_%D0%90%D0%BB%D0%B5%D0%BA%D1%81%D0%B5%D0%B9_%D0%9C%D0%B8%D1%85%D0%B0%D0%B9%D0%BB%D0%BE%D0%B2%D0%B8%D1%87). См. «[Математика и интуиция](https://postnauka.org/video/34416)», «[Абстрактное и конкретное в математике](https://postnauka.org/video/41678)» и другие лекции.

Безусловно, есть еще много причин --- на математике работаю все цифровые устройства и современные алгоритмы, окружающие нас повсюду, являясь формальной наукой, она знакомит нас с логическими рассуждениями и доказательствами, позволяет изучать мир за пределами нашего перцептивного опыта[^semikhatov-discoveries] и т.д. Частично мы попробуем прикоснуться в рамках данной книги.

[^semikhatov-discoveries]: На тему открытий и предсказаний силами математики безумно интересно рассказывает всё тот же А. М. Семихатов. Есть два варианта примерно одной и той же лекции: [для всех](https://youtu.be/z7mHlwyY2vs?si=t63nGLwbsv_8u4ED) и [для программистов](https://youtu.be/-98It-7EDOo?si=nJKiP-n3UIunaTbd).


## Размышления о «математической тревожности»


