# Случайные величины {#randvalues}

{{< include other/_symbols.qmd >}}

```{r opts, echo=FALSE, eval=TRUE, message=FALSE, warning=FALSE, error=FALSE}
knitr::opts_chunk$set(echo=TRUE, eval=TRUE, message=FALSE, warning=FALSE, error=FALSE)
```


:::{.intro}
В предыдущей главы мы выстроили теоретико-множественный фундамент теории вероятности. Это была полезная с точки зрения создания последовательной и непротиворечивой теории деятельность, однако, как вы могли заметить, в работе со множествами возникает ряд проблем, приходится вводить разные дополнительные определения, что усложняем нам жизнь. Возникает естественная потребность выстроить новый объект, называемый случайной величиной.
:::

Зачем нам нужны случайные величины? Ну, во-первых, математика, чьей частью является теория вероятности, не очень-то понимает, как работать в таким объектом, как «элементарный исход». «На игральном кубике выпало 6 очков» --- довольно странный математический объект. Давайте введем такую конструкцию, которая будет сопоставлять элементарному исходу $\omega$ некоторое число $\xi(\omega)$:

$$
\omega \mapsto \xi(\omega) \in \setR
$$

Тогда мы сможем работать с числами, а это понятно как делать с помощью математики. В частности, событию «на игральном кубике выпало 6 очков» довольно естественно сопоставляется число $6$, а событию «респондент при ответе на вопрос с помощью шкалы Ликерта выбрал 5» --- число $5$.

Кажется, что мы занимаемся какой-то ерундой, потому что это же и так очевидно. Отчасти --- да. К тому же, в психологических исследованиях сам процесс измерения обеспечивает нам сопоставление случайного события с некоторым числом, поэтому мы редко задумываемся о том, что там с точки зрения теории вероятности происходит. Однако всё довольно просто, когда мы говорим о дискретных вероятностных пространствах --- игральный кубик и шкала Ликерта --- а когда мы будем иметь дело с непрерывным вероятностным пространством --- например, при том же измерении времени реакции --- там ещё неизвестно, что будет происходить, хотя как будто бы более-менее ясен сам процесс измерения времени реакции.

Ну, и кроме того, раз уж мы приблизились к серьезной математике, то необходимо новый вводимый объект формально определить, изучить его свойства --- вдруг там обнаружится что-то важное с точки зрения практики? А случайные величины для практики край не важны --- собственно, в приложении к практике теория вероятности представляет собой теорию случайных величин.

Итак, мы решаем ввести конструкцию $\omega \mapsto \xi(\omega) \in \setR$. Это значит, что возникает функция $\xi : \Omega \to \setR$. Далее возникают вопросы, связанные с тем, что нам необходимо считать вероятность ---- чему равны, например,

* $\prob \big\{ \omega \such \xi(\omega) = x \big\} \equiv \prob \big( \xi(\omega \big) = x)$,
* $\prob \big\{ \omega \such x_1 < \xi(\omega) < x_2 \big\} \equiv \prob \big( x_1 < \xi(\omega) < x_2 \big)$?

Поскольку вероятность существует только для элементов $\Fcal$, мы должны быть уверенны, что

* $\big \{ \omega \such \xi(\omega) = x \big\} \in \Fcal$,
* $\big \{ \omega \such x_1 < \xi(\omega) < x_2 \big\} \in \Fcal$.

Соответственно, нужно, как мы делали ранее, сформировать минимальный набор требований к множествам, из которых будут следовать все остальные.

:::{#def-rand-value}
**Случайной величиной** над вероятностным пространством $(\Omega, \Fcal, \prob)$ называется функция $\xi: \Omega \to \setR$, такая что

$$
\begin{gather}
\forall x \in \setR \, \big\{ \omega \such \xi(\omega) < x \big\} \in \Fcal \\
\Updownarrow \\
\exists \, \prob \big( \xi(\omega) < x\big) \equiv \prob \big\{ \omega \such \xi(\omega) < x \big\} \\
\Updownarrow \\
\forall x \in \setR \exists \, F(x) = \prob \big(\xi(\omega) < x \big)
\end{gather}
$$

где $F(\cdot) : \setR \to [0, 1]$ называется **функцией распределения**.
:::

:::{.remark}
С точки зрения теории меры случайная величина является *измеримой функцией*.
:::

:::{.remark}
Теория вероятности не изменится, если в условии на множества $\forall x \in \setR \, \big\{ \omega \such \xi(\omega) < x \big\} \in \Fcal$ изменить знак неравенства. Все три варианта

$$
\begin{aligned}
&\big\{ \omega \such \xi(\omega) \leq x \big\} \in \Fcal \\
&\big\{ \omega \such \xi(\omega) > x \big\} \in \Fcal \\
&\big\{ \omega \such x_1 < \xi(\omega) < x_2 \big\} \in \Fcal
\end{aligned}
$$

приводят к одной и той же теории вероятности.
:::

Если задано вероятностное пространство $(\Omega, \Fcal, \prob)$, то любая случайная величина $\xi$ индуцирует новое вероятностное пространство $\big (\setR, \mathcal B, F_\xi(\cdot) \big)$:

$$
(\Omega, \Fcal, \prob) \overset{\xi}{\longrightarrow} \big (\setR, \Bcal, F_\xi(\cdot) \big)
$$

Возникший объект $\Bcal$ --- это борелевская $\sigma$-алгебра подмножеств $\setR$, то есть $\sigma$-алгебра, такая что (1) $\forall x \, (-\infty, x) \in \Bcal$ и (2) она минимальная из всех возможных $\sigma$-алгебр. Эта структура чрезвычайно обширна, но всё же не совпадает со множеством всем подмножеств $\setR$.

Таким образом, имея вероятностное пространство $\big (\setR, \Bcal, F_\xi(\cdot) \big)$ мы можем говорить и том, что

$$
\prob(-\infty, x) = \prob \big( \xi(\omega) < x \big) = F(x)
$$

:::{#def-rand-value-discrete}
Распределение случайной величины $\xi$ называется **дискретным**, если

$$
F(x) = \sum_{k \suchd x_k < x} p_k,
$$

где $\big\{ (x_k, p_k) \big\}_{k=1}^N, \, N \leq \aleph_0$ --- конечный или счётный набор, $p_k > 0$, $\sum_{k=1}^N p_k = 1$.
:::

Если $x_k < x_{k+1} \forall k$, то $F(x) = \const$ при $x \in (x_k, x_{k+1})$, $F(x_n + 0) - F(x_n) - 0 = p_k$.


:::{#def-rand-value-continuous}
Случайная величина $\xi$ имеет **абсолютно непрерывное** распределение, если

$$
F(x) = \int_{-\infty}^x \dens(z)dz, \, x \in \setR,
$$
где $\dens(\cdot)$ --- некоторая функция, $\dens(z) > 0$, $\int_{-\infty}^\infty \dens(z)dx = 1$.

Функция $\dens(\cdot)$ называется **плотностью распределения**.
:::

$F(\cdot)$ непрерывна в каждой точке $x$ ($\forall x \in \setR$) и $F'(x) = \dens(x)$.


## Общие свойства функций распределения

:::{#prp-F-monotonous}
$F(\cdot)$ не убывает.
:::

:::{#prp-F-contleft}
$F(\cdot)$ непрерывна слева.
:::

:::{#prp-F-infty}
$F(-\infty) = 0$, $F(+\infty) = 1$
:::





```{=html}
<script type="text/javascript" src="./js/chapter.js"></script>
```
