project: 
  type: website

website: 
  title: "WLM SDARP // Assessment"
  navbar: 
    left:
      - href: index.qmd
        text: Home

format: 
  html: 
    # theme: 
    #   - ../shared/css/common.scss
    toc: true