project:
  type: website
  preview:
    port: 5050

website:
  title: "WLM SDARP"
  navbar:
    left:
      - text: "Home"
        href: index.qmd
      - text: "Book"
        href: ""
      - text: "Tests"
        href: ""
  navbar:
    left:

format:
  html:
    # theme:
    #   - ../shared/css/common.scss
    toc: true
